### ISSUE TITLE
How do we train the Rasa core in addition to Rasa NLU?

### ISSUE THREAD

**Issue by wanteetGithub** [paschmann/rasa-ui#175] opened 2019-03-14 16:24 UTC
Hello,

Q1. When I press the "start training" button, it trains only the Rasa NLU. Does Rasa-UI support training of the rasa-core as well? If yes, then how do we train the Rasa Core using the Rasa-UI.  So even after enabling the Rasa Core in the agent settings, the core is not getting trained. Only the NLU is. Please advise.

Q2. How do we get the slot values using Rasa UI from the Rasa Core? Right now, the server just returns the response text without taking into consideration the slot values.

Thank you.

**Comment by pradeepmvn** [comment] 2019-03-14 17:25
@wanteetGithub duplicate of #174 ?

**Comment by paschmann** [comment] 2019-08-30 01:47
Hi @wanteetGithub - the new version of Rasa UI now supports this.

**Closed by paschmann** 2019-08-30 01:47 UTC
